deployment:
  allowed_users:
  - kaplunov@gmail.com
  - ikaplunov@gmail.com
  - ilona@blueappledesign.com
  project_id: rental-pnl-automation
  region: us-central1
downloads_dir: ./downloads
properties:
- 154 Santa Clara
- 11873 E MapleWood
- 30 Bishop Oak
property_sheets:
  11873 E Maplewood:
    spreadsheet_id: 19kqGWWNS-CtohFc8SIL4lm3ow5NJRnuQd80SIAToPgg
  154 Santa Clara:
    spreadsheet_id: 12d83Pjnl6fCmtqNhjPhnoyFKZlLA7RR0FdhVM0Ox8Zw
  30 Bishop Oak:
    spreadsheet_id: 1DsgnBdpUHcK4fzHi6FmW6X3NxoPi8vGwrLJB6wS6nz4
skip_descriptions:
- CHASE CREDIT CRD EPAY
split_rules:
  BILL PAY Juan Santiago:
  - amount: -340.0
    parts:
    - amount: -140.0
      category: Landscaping
      property: 154 Santa Clara
    - amount: -200.0
      category: Landscaping
      property: 30 Bishop Oak
  - default:
      category: Landscaping
      property: 30 Bishop Oak
spreadsheet_id: 1hfScemwFS_JDDjJO2P_Nnf4a9yCCMF8e4wQjJSjhHNE
